# Generated by Django 6.0.2 on 2026-02-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(blank=True, help_text='Where the lead came from Landing', max_length=100)),
                ('contacted', models.BooleanField(default=False, help_text='Has Denisa already contacted this lead?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
