# Generated by Django 6.0.2 on 2026-02-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name show to customers', max_length=255)),
                ('descriptions', models.TextField(help_text='Detailed product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('product_type', models.CharField(choices=[('digital', 'Digital product'), ('jewelry', 'Jewelry'), ('service', 'Service')], max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is product visible in shop')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updatet_at', models.DateTimeField(auto_now=True)),
                ('digital_file', models.FileField(blank=True, help_text='File available after payment', null=True, upload_to='digital_products/')),
            ],
        ),
    ]
